# Generated by Django 5.1.3 on 2025-04-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_profession_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('normal', 'Normal'), ('professional', 'Professional'), ('admin', 'Administrator')], default='normal', max_length=20),
        ),
    ]
