# Generated by Django 5.1.3 on 2025-04-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='login_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
